spring:
  profiles:
    active: local
  application:
    name: core-api
  config:
    import:
      - logging.yml
      - monitoring.yml
      - db-core.yml
  web:
    resources:
      add-mappings: false

---
spring:
  config:
    activate:
      on-profile: local


---
spring:
  config:
    activate:
      on-profile: local-dev


---
spring:
  config:
    activate:
      on-profile: dev


---
spring:
  config:
    activate:
      on-profile: prod
